# Site settings
title: ShelomentsevD
description: >
  Shelomentsev Dmitriy personal blog.
  Личный блог Шеломенцева Дмитрия.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "shelomentsevd.github.io" # the base hostname & protocol for your site

author:
  fullname: Shelomentsev Dmitriy
  github: shelomentsevd
  disqus: shelomentsevdgithubio

google_analytics: 'UA-73125530-1'

# Build settings
markdown: kramdown
